### ISSUE TITLE
Complains of missing MySQL extension, which is there!

### ISSUE THREAD

**Issue by greencopper** [osCommerce/oscommerce2#368]
![80f99c16-7701-11e5-91bf-b800d4aa84bb](https://cloud.githubusercontent.com/assets/1302896/10858466/85d006d8-7f55-11e5-94e3-8517d63e4936.png)

**Comment by markkevans** [comment]
You can fix this with the code change below, this is in the file catalog/install/templates/pages/index.php

```php
diff --git a/catalog/install/templates/pages/index.php b/catalog/install/templates/pages/index.php
index 81f0416..b1a4b3a 100644
--- a/catalog/install/templates/pages/index.php
+++ b/catalog/install/templates/pages/index.php
@@ -58,7 +58,7 @@
       }
     }
 
-    if (!extension_loaded('mysql')) {
+    if (!extension_loaded('mysql') || !extension_loaded('mysqli')) {
       $warning_array['mysql'] = 'The MySQL extension is required but is not installed. Please enable it to continue installation.';
     } 
```

**Comment by timint** [comment]
Shouldn't it be?
```if (!extension_loaded('mysql') && !extension_loaded('mysqli')) {```

**Comment by markkevans** [comment]
@timint Using && would check that neither of the extensions were enabled, where in reality you can have either of the extensions loaded and it will work

**Comment by timint** [comment]
I'm thinking; why would you display a warning if one of the two components is present?

**Comment by raykai** [comment]
im having this prob too should be fix by now ...

**Comment by SChalice** [comment]
Seriously, please update the source code guys, this is a very old and very severe bug.....


if (!extension_loaded('mysql') && !extension_loaded('mysqli'))

**Comment by timint** [comment]
I tried pointing this out but Mark says different.

**Comment by SChalice** [comment]
Mark is clueless or paid off.

**Comment by MOPS-DanCole** [comment]
Doesn't his fix posted above work?

**Comment by timint** [comment]
@MOPS-DanCole 

Does this look right to you?
`!extension_loaded('mysql') || !extension_loaded('mysqli')`

If at least one component is missing it will generate a warning. So it requires both mysql and mysqli at the same time to pass.

**Comment by MOPS-DanCole** [comment]
It doesn't but I don't know what all comes before it.  Did you try it?

**Comment by nasirkhan** [comment]
facing the same issue, did anyone find the solution yet?

**Comment by timint** [comment]
Ffs guys, if both cases are negative show a warning:

if (!extension_loaded('mysql') && !extension_loaded('mysqli')) {

This is a complete blocker for everyone, I'm surprised it's not fixed yet.

**Comment by smachaje** [comment]
This error showed up for me even though mysqli was configured correctly.  Once I changed configuration.php in includes and set the correct database name and user/pass, it worked ok.  Temporarily rename install directory to see the actual error message.  The install script didn't set the database name correctly in the config file.

**Comment by haraldpdl** [comment]
This has been fixed in v2.4 with PDO, and in v2.3 with the following commit:

https://github.com/osCommerce/oscommerce2/commit/d7f47032afbda82c6342c6fc83777de30a36b5b8

**Comment by Pitmaster** [comment]
The && worked for me! Thank you all for the post.

Pit

**Comment by martin03** [comment]
Version v2.3
line 146
`if (!extension_loaded('mysql')) {`
should become
`if (!extension_loaded('mysql') && !extension_loaded('mysqli')) {`

**Comment by KaitoTriforce** [comment]
Over one year after this trivial problem about a single line of code was reported, the current downloadable osCommerce v2.3.4 still has the same issue.

**Comment by MOPS-DanCole** [comment]
Did you add the fix posted by Harald above?

**Comment by haraldpdl** [comment]
This will be pushed out soon in v2.3.5.

**Comment by olivierpons** [comment]
I'm trying to teach my students the osCommerce installation and the 2.3.4 has this bug, more than one year later, and is the #1 download thing...

**Comment by duttaa19** [comment]
&& works for me not ||.
Thanks.

**Comment by mcasantosh** [comment]
Timint is correct.

We should modifying the following in catalog/install/templates/pages/index.php page

#if (!extension_loaded('mysql')) {
  if (!extension_loaded('mysql') && !extension_loaded('mysqli')) {
    $warning_array['mysql'] = 'The MySQL extension is required but is not installed. Please enable it to continue installation.';
  }

This worked for me.

**Comment by jodanilmoro** [comment]
> if (!extension_loaded('mysql') && !extension_loaded('mysqli')) {

MEJOR RESPUESTA! FUNCIONÓ
