### ISSUE TITLE
PHP version and install oscommerce pb

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#369]
There the information when I tried to install osc.

Serveur HTTP : 	Apache/2.4.12 (Ubuntu)
Version PHP : 	5.6.11-1ubuntu3.1 (Zend : 2.6.0)

Notice: Use of undefined constant DB_SERVER - assumed 'DB_SERVER' in /home/www/test/ms234/includes/OSC/OM/Db.php on line 32

Notice: Use of undefined constant DB_SERVER_USERNAME - assumed 'DB_SERVER_USERNAME' in /home/www/test/ms234/includes/OSC/OM/Db.php on line 36

Notice: Use of undefined constant DB_SERVER_PASSWORD - assumed 'DB_SERVER_PASSWORD' in /home/www/test/ms234/includes/OSC/OM/Db.php on line 40

Notice: Use of undefined constant DB_DATABASE - assumed 'DB_DATABASE' in /home/www/test/ms234/includes/OSC/OM/Db.php on line 44

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2005] Unknown MySQL server host 'DB_SERVER' (2)' in /home/www/test/ms234/includes/OSC/OM/Db/MySQL.php:49 Stack trace: #0 /home/www/test/ms234/includes/OSC/OM/Db/MySQL.php(49): PDO->__construct('mysql:dbname=DB...', 'DB_SERVER_USERN...', 'DB_SERVER_PASSW...', Array) #1 /home/www/test/ms234/includes/OSC/OM/Db/MySQL.php(22): OSC\OM\Db\MySQL->connect() #2 /home/www/test/ms234/includes/OSC/OM/Db.php(60): OSC\OM\Db\MySQL->__construct('DB_SERVER', 'DB_SERVER_USERN...', 'DB_SERVER_PASSW...', 'DB_DATABASE', NULL, Array) #3 /home/www/test/ms234/includes/OSC/Sites/Shop/Shop.php(27): OSC\OM\Db::initialize() #4 /home/www/test/ms234/includes/OSC/OM/SitesAbstract.php(29): OSC\Sites\Shop\Shop->init() #5 /home/www/test/ms234/includes/OSC/OM/OSCOM.php(56): OSC\OM\SitesAbstract->__construct() #6 /home/www/test/ms234/includes/OSC/OM/OSCOM.php(27): OSC\OM\OSCOM::setSite(NULL) #7 /home/www/test/ms234/install/includes/application.php(24): OSC\OM\OSCOM::initialize() #8 in /home/www/test/ms234/includes/OSC/OM/Db/MySQL.php on line 49

**Comment by Gergely** [comment]
Development version is under construction

comment out the following two lines in install/includes/application_top.php

`  //  OSCOM::initialize();
  //  OSCOM::setSite('Setup');`

**Comment by oitsuki** [comment]
Yes I know, just for information

**Comment by haraldpdl** [comment]
Thanks for the report, this has already been fixed.
