### ISSUE TITLE
Use of undefined constant DIR_WS_INCLUDES

### ISSUE THREAD

**Issue by katapofatico** [osCommerce/oscommerce2#370]
Hello :) 

On @gburton commit ["Deprecate includes"](https://github.com/osCommerce/oscommerce2/commit/e4e1d478daf32c0102c00b83e0eb9fe845413995) he removes the definition of DIR_WS_INCLUDES on [includes/configure.php](https://github.com/osCommerce/oscommerce2/commit/e4e1d478daf32c0102c00b83e0eb9fe845413995#diff-bb5f6f689189bffcd46ee3e5e3c625bd), but several uses persists on same file, next lines. This is breaking the installation of master branch.
```
Notice: "Use of undefined constant DIR_WS_INCLUDES - assumed 'DIR_WS_INCLUDES' in /var/www/html/catalog/includes/configure.php on line 28"
```
Thanks for reply

**Comment by Gergely** [comment]
Did you install again the shop after merge the commit?

**Comment by haraldpdl** [comment]
Thanks for the report. This seems to be fixed already.
