### ISSUE TITLE
Cannot access admin features on 2.3.4

### ISSUE THREAD

**Issue by astecme** [osCommerce/oscommerce2#371]
In order to test with different levels of PHP I have had create a subdomain. I installed OsCommerce via the subdomain and it all appears to work however when I try to access the administration section the load fails and amin/login does not open. My browser says that there is an eternal redirect loop which has been stopped. Can anyone help me please.

**Comment by haraldpdl** [comment]
Please search or post about this in the forum as it is a configuration issue. Thanks.
