### ISSUE TITLE
Apps : $result  - return nothing (osc 2.4)

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#375]
What is the result of  return $result; in OM/Apps ?

    public static function getModuleClass($module, $type)
    {
        if (!Registry::exists('ModuleType' . $type)) {
            $class = 'OSC\OM\Modules\\' . $type;

            if (!class_exists($class)) {
                trigger_error('OSC\OM\Apps::getModuleClass(): ' . $type . ' module class not found in OSC\OM\Modules\\');

                return $result;
            }

            Registry::set('ModuleType' . $type, new $class());
        }

        $OSCOM_Type = Registry::get('ModuleType' . $type);

        return $OSCOM_Type->getClass($module);
    }

**Comment by Gergely** [comment]
it is a good question
