### ISSUE TITLE
SessionId in GET Parameters when SESSION_FORCE_COOKIE_USE is TRUE

### ISSUE THREAD

**Issue by Hrnkas** [osCommerce/oscommerce2#376]
The function "tep_hide_session_id" prints the hidden variable containing the SessionId even if the SESSION_FORCE_COOKIE_USE is set to 'True'. This causes Redirect 302 to the FILENAME_DEFAULT in the "tep_session_start" function, the first time the page is loaded and the session is created.

Reproduce:
Use the search form on the start page (index.php) the very first time after cookies have been cleared on the browser. The advanced_search_result.php is called with SessionId in a GET variable, thus causing redirect to the index.php. This happens only if the SESSION_FORCE_COOKIE_USE is True.

Proposal:
Change tep_hide_session_id like this:
 
    function tep_hide_session_id() 
    {

        global $session_started, $SID;
    
        //session id is always in cookie
        if (SESSION_FORCE_COOKIE_USE == 'True')
        {
            return '';
        }
    
        if (($session_started == true) && tep_not_null($SID)) {
            return tep_draw_hidden_field(tep_session_name(), tep_session_id());
        }

    }

**Comment by Gergely** [comment]
SESSION_CHECK_SSL_SESSION_ID should be **false**

What is your **Check SSL Session ID**  value?

**Comment by Hrnkas** [comment]
It is False. The SSL is not activated on this Webshop.

**Comment by Gergely** [comment]
Thanks for the reporting!

I can and can not reproduce the same issue. I have tried on two different v2.3.4 test system.
Same server, similar codebase (BS vs Official), same config but different results..

Wierd problem.

Could you reproduce on https://demo.oscommerce.com ?

I think the updated non-ssl versions has only problem.

**Comment by Gergely** [comment]
@Hrnkas Your solution works well. Thanks!

**Comment by haraldpdl** [comment]
Commit for v2.4:
https://github.com/haraldpdl/oscommerce2/commit/ea4c54074bcc8558921d21fe7b12ae4b4b9c58fc
