### ISSUE TITLE
PHP7 session pb - login in catalog (osc 2.4)

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#382]
It seems a problem with sessions in php 7

Warning: session_regenerate_id(): Session callback expects true/false return value
Warning: session_regenerate_id(): Session object destruction failed. ID: user (path: /tmp/)

The rpoblem apear when you want to log in on catalog
line 127 :   session_regenerate_id(true);

**Comment by Gergely** [comment]
@oitsuki is it a xamp specific problem? I can not reproduce on wamp.

**Comment by oitsuki** [comment]
No it's not on wamp but on ubuntu xenial 
PHP Version 	7.0.4-7ubuntu2 		
Server configuration 	
Register Globals 	Off 	
Magic Quotes 	Off 	
Files upload 	On 	
Session auto start 	Off 	
Session use trans sid 	Off

**Comment by haraldpdl** [comment]
Thanks for the report. This has been fixed already.
