### ISSUE TITLE
Deprecated Class constructors

### ISSUE THREAD

**Issue by Gergely** [osCommerce/oscommerce2#383]
> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP

The backwards compatibilty with older php versions enable to use **__construct()** because stated v2.4 version will not be compatible older v2.3 components.

**Comment by Gergely** [comment]
fixed

**Comment by golith** [comment]
Could I have a look at the code please :-)

**Comment by Gergely** [comment]
@golith 

v2.4 is figured out in development branch so I couldnt give exact commits.
v2.3.5 core muted with deprecated errors.
