### ISSUE TITLE
PHP 7 Session Pb (osc 2.4)

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#384]
Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/www/test/oscommerce2/catalog/includes/configure.php:31) in /home/www/test/oscommerce2/catalog/includes/functions/sessions.php on line 108

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/www/test/oscommerce2/catalog/includes/configure.php:31) in /home/www/test/oscommerce2/catalog/includes/functions/sessions.php on line 108

see also : PHP7 REWRITE SESSION 2.3.x and 2.4 issue

**Comment by haraldpdl** [comment]
There was probably extra whitespace in configure.php - this file no longer exists in the latest set of commits for v2.4.0b1.
