### ISSUE TITLE
PHP 7 - MYSQL 7  - SQLSTATE[HY093]: Invalid parameter number:  with modules.php (osc 2.4)

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#386]
Some errors seems appear since MYSQL 7 and PHP 7  is out.

This pb come from modules.php with the install function, doesn't work now but work fine php 5. and Mysql 5.x.

Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in /home/www/osc/includes/OSC/OM/DbStatement.php on line 97

**Comment by haraldpdl** [comment]
Please submit this issue again if the problem persists with the latest code changes. Thanks.
