### ISSUE TITLE
languages.php

### ISSUE THREAD

**Issue by mcheja10** [osCommerce/oscommerce2#389]
On multiple environments i am getting an error in nginx logs that is bringing back a blank value for language in application_top.php.  Any help please!

Here is the beginning of the error.
PHP message: PHP Fatal error:  require(): Failed opening required 'includes/languages/.php' (include_path='.:/usr/share/php') in /var/www/shop.thisoldfarminc.com/htdocs/admin/pos/includes/application_to

**Comment by elray** [comment]
Gb to 

Sent from my Xperia Z2 on O2

---- Jason Mc wrote ----

**Comment by haraldpdl** [comment]
Please search or post about this in the forum as it is not a bug but a server configuration issue. Thanks.
