### ISSUE TITLE
MYSQL 7 - Pb with strict mode Insert data

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#392]
Some errors can appear if you use mysql with strict mode.
Some explanation you can read here : https://serversforhackers.com/mysql-utf8-and-indexing
For example I have this probem with product_description table when I insert a new product
`warning: PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '21-2' for key 'PRIMARY' `
Tested on 2.4

**Comment by haraldpdl** [comment]
That error seems to be related to a duplicate primary key value instead of strict mode. Please submit another issue if the problem persists and post which query is affected. Thanks.
