### ISSUE TITLE
MYSQL 7 strict mode : Int and float mandatory

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#393]
The request for 2.4 must write like this (specifically if it's integer or decimal)

```
  $OSCOM_Db->save('specials', [
                'products_id' => (int)$products_id,
                 'specials_new_products_price' => (float)$specials_price, 
                'specials_date_added' => 'now()',
                 'status' => 1
                 ]
            );

```

**Comment by Gergely** [comment]
What about?

```sql
UPDATE IGNORE..
INSERT IGNORE ..
```
Strict mode break the installation at this moment and do a lot of trouble.

I think the best way to follow the strict mode inmediately to prevent conflicts.

**Comment by haraldpdl** [comment]
It's totally fine to pass a string "1" as an integer to MySQL in strict sql mode. An error only occurs if the value can not be casted to an integer (eg, "1a").
