### ISSUE TITLE
setPageSet error for osc 2.4

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#395]
`Fatal error: Uncaught Error: Call to a member function setPageSet() on null`

If you tried to change the money, you can have this problem.

`$Qlisting->setPageSet(MAX_DISPLAY_SEARCH_RESULTS);`

Could you confirm the problem ?

**Comment by haraldpdl** [comment]
This seems to have been fixed in the latest set of changes for v2.4.0b1.
