### ISSUE TITLE
Tutorial upgrade to oscommerce 2.3.3.4

### ISSUE THREAD

**Issue by marcelomaeda** [osCommerce/oscommerce2#398]
Hi,

This tutorial is perfect: https://github.com/osCommerce/oscommerce2/commit/784144ad78c6d358da6b76570def4f2c9f94b0b7#diff-359215d6efaf57b13f3211407e3312f6L394

Do you have the tutorial for upgrade to the version 2.3.3.4 ?

Thank you.

**Comment by haraldpdl** [comment]
Please check the releases notes here:

https://library.oscommerce.com/Online&en&oscom_2_3&release_notes
