### ISSUE TITLE
Customers back out of Order but it still gets added to order history

### ISSUE THREAD

**Issue by bshoop1988** [osCommerce/oscommerce2#409]
I'm using osCommerce Online Merchant v2.3.4. 
I have the Discounts for BS Addon.

Basically, customers add their items to cart, go to check out, than get to the confirmation page after the payment type page, than they back out, and don't confirm it at the last page.  But it still adds the order to the order history as if they did confirm it.  Trying to figure out whats wrong for 3 hours, need help please.

**Comment by haraldpdl** [comment]
This is not a core feature of OSCOM. Please search or post about the problem you are experiencing to our forums at:

http://forums.oscommerce.com
