### ISSUE TITLE
PayPal Plugin calling tep_href_link - function not found

### ISSUE THREAD

**Issue by DasWookie** [osCommerce/oscommerce2#444]
I'm running the latest code as of 10/29/16 and am trying to install the paypal v3.2 module. I'm running into an issue however, in that it's calling function tep_href_link, and near as I can tell, that function doesn't seem to exist... well... anywhere anymore. I'm seeing references to it in the 2.2rc2a readme changelog, but a grep of the codebase can't find the function. I had to manually insert the osc_configuration parameters, or the paypal module completely failed to be loaded on the Legacy->Modules->Payment screen. Once I copy the 4 PayPal files into the respective target locations, I see the Install Module tab correctly increments by one (from default of 3 to 4) but then I hit the problem with the module at:
Call to undefined function tep_href_link() with /catalog/includes/modules/payment/paypal_standard.php on line 980

of:
$test_url = **tep_href_link**(FILENAME_MODULES, 'set=payment&module=' . $this->code . '&action=install&subaction=conntest');

To fetch the code for my install I just did a get clone of the repo. I fetched the codebase for 2.3.4, 2.3.3,4, 2.2rc2a, and 2.2rc2 tags as well... recursive grep of those tags is also failing to find the tep_href_link function, so I'm completely baffled!

What am I missing here??? Has the function been renamed or deprecated?

**Comment by haraldpdl** [comment]
http://forums.oscommerce.com/topic/410380-paypal-plugin-calling-tep-href-link-function-not-found/
