### ISSUE TITLE
PHP Fatal error 'There is no suitable CSPRNG installed on your system'

### ISSUE THREAD

**Issue by Moxamint** [osCommerce/oscommerce2#479]
Shop front won't load with HTTP ERROR 500.  The following error message was logged  in admin:

`[12-Nov-2016 12:25:16 Asia/Taipei] PHP Fatal error:  Uncaught exception 'Exception' with message 'There is no suitable CSPRNG installed on your system' in /home/httpd/vhosts/abc.com/subdomains/abc/httpdocs/includes/third_party/random_compat/random.php:185`

and followed by stack traces.

**Comment by haraldpdl** [comment]
Could you perform the following change to see if it helps:

https://github.com/paragonie/random_compat/commit/67f5061250a925b1de5d5dd524ac26a024493ed9#diff-3389ff8e306f9430cb1a83d3ef20c131

That file exists in:

catalog/includes/third_party/random_compat/random.php

v2.0.3 of that library is bundled with our release. That change went into v2.0.4.

**Comment by Moxamint** [comment]
I confirm that the change provided from that link fixes the issue.

Thank you!

**Comment by haraldpdl** [comment]
Thanks! This will be fixed in the next beta release.
