### ISSUE TITLE
PHP Warning:  PDO::__construct()

### ISSUE THREAD

**Issue by MOPS-DanCole** [osCommerce/oscommerce2#482]
Just installed Joli and performed the update to 2.4.1.  Everything worked extremely well and looks great.  Excellent work guys!   I poked around a bit and the only thing I noticed out of the norm is this warning message.  It might be something unique to my set up but in case it helps, here it is.

[13-Nov-2016 03:52:14 Europe/Berlin] PHP Warning:  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/mysite/mydirectory/catalog/includes/OSC/OM/Db/MySQL.php on line 58

Dan

**Comment by haraldpdl** [comment]
Hi Dan..

Does that error occur often? Do you know when and how it occurred?

**Comment by MOPS-DanCole** [comment]
Harald I can't seem to reproduce it.  I'm thinking it was generated on the install and update to version 2.4.1.  I'll watch for it when I do another update or install and hopefully can get you a bit more to go on.  While I was trying to reproduce this I did come up with another issue which I can in fact reproduce....

This error message gets logged when I click .....  Admin ->  Legacy -> Localization -> Currencies 

[14-Nov-2016 22:02:46 America/Toronto] PHP Notice:  DateTime:  () cannot be formatted to Y-m-d H:i:s in /home/mysite/mydirectory/catalog/includes/OSC/OM/DateTime.php on line 52

**Comment by haraldpdl** [comment]
Hi Dan..

The PDO error more than likely occurred during the installation procedure where an incorrect database server address may have been entered or the database connection was not available at the time. This is purely an informative error message and is safe to ignore/delete as it has already been fixed (a correct database server address was entered or the database server came back up).

Regarding the datetime notice, could you open a new issue about that? Thanks!

**Comment by haraldpdl** [comment]
The installation routine in v2.4.3 no longer logs database connection errors when trying to connect to the database server for the first time with the parameters entered. Errors will start to be logged after the first successful connection attempt to the database server and when the database schema is being imported.
