### ISSUE TITLE
New category image upload - file name length

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#494]
Attempted to upload a .png file for new category. File name was 68 characters long, which resulted in a 500 error. 

From log file:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'categories_image' at row 1' in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php:97
Stack trace:
#0 /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php(97): PDOStatement->execute(NULL)
#1 /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php(273): OSC\OM\DbStatement->execute()
#2 /home/somewebsite/public_html/2point4/admin/categories.php(96): OSC\OM\Db->save('categories', Array, Array)
#3 {main}
  thrown in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php on line 97

**Comment by haraldpdl** [comment]
🍺  fixed in #535
