### ISSUE TITLE
Cannot delete categories

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#495]
Attempting to delete categories results in a 500 error.

From error log:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cd.categories_name' in 'field list'' in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php:97
Stack trace:
#0 /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php(97): PDOStatement->execute(NULL)
#1 /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php(223): OSC\OM\DbStatement->execute()
#2 /home/somewebsite/public_html/2point4/admin/includes/functions/general.php(96): OSC\OM\Db->get('categories_desc...', 'cd.categories_n...', Array)
#3 /home/somewebsite/public_html/2point4/admin/categories.php(108): tep_get_category_tree('17', '', '0', '', true)
#4 {main}
  thrown in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php on line 97

**Comment by scottcwilson** [comment]
Fixed by PR #532.
