### ISSUE TITLE
Specials page not working

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#497]
Navigate to specials page - only header and title appears (no left column or products)

Error log:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tonerpak_2point4.products_description' doesn't exist' in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php:97
Stack trace:
#0 /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php(97): PDOStatement->execute(NULL)
#1 /home/somewebsite/public_html/2point4/specials.php(112): OSC\OM\DbStatement->execute()
#2 {main}
  thrown in /home/somewebsite/public_html/2point4/includes/OSC/OM/DbStatement.php on line 97

**Comment by haraldpdl** [comment]
Duplicate #473
