### ISSUE TITLE
Link to customer not working.

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#498]
Click on a customer on admin home page (under heading 'Customers'), goes to admin/customers.php but page is blank.

from error file:

PHP Fatal error:  Call to undefined function jscon_encode() in /home/somewebsite/public_html/2point4/admin/customers.php on line 279

(fixing that typo results in another error: PHP Fatal error:  Call to undefined function json_enccode() in /home/somewebsite/public_html/2point4/admin/customers.php on line 296)

**Comment by Gergely** [comment]
Thanks the report!
Same issue is found in line 300
