### ISSUE TITLE
Customer emails have no new lines

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#499]
Customer emails sent have no new lines so everything is on one line. 

Displays in Thunderbird as:

2point4 ------------------------------------------------------ Order Number: 1 Detailed Invoice: https://www.somewebsite.com.au/2point4/account_history_info.php?order_id=1 Date Ordered: Tuesday 15 November, 2016 The comments for your order are Your order has been updated to the following status. New status: Processing Please reply to this email if you have any questions.

Raw text of email:

Return-Path: <sales@somewebsite.com>
Delivered-To: frank@someotherwebsite.com.au
Received: from somewebsite.com
	by CentOS6-VPS (Dovecot) with LMTP id SgWeMOZkKlgpUwAAhd2+mg
	for <frank@someotherwebsite.com.au>; Tue, 15 Nov 2016 12:29:10 +1100
Return-path: <sales@somewebsite.com>
Envelope-to: frank@someotherwebsite.com.au
Delivery-date: Tue, 15 Nov 2016 12:29:10 +1100
Received: from somewebsite by someotherwebsite.com with local (Exim 4.87)
	(envelope-from <sales@somewebsite.com>)
	id 1c6SYg-0005XG-M4
	for frank@someotherwebsite.com.au; Tue, 15 Nov 2016 12:29:10 +1100
To: "Frank Lastname" <frank@someotherwebsite.com.au>
Subject: Order Update
X-PHP-Script: www.somewebsite.com/2point4/admin/orders.php for 203.206.167.119
X-Mailer: osCommerce
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=_____MULTIPART_MIXED_BOUNDARY____"
Content-Transfer-Encoding: 7bit
From: "2point4" <sales@somewebsite.com>
Message-Id: <E1c6SYg-0005XG-M4@somewebsite.com>
Date: Tue, 15 Nov 2016 12:29:10 +1100

This is a multi-part message in MIME format.

--=_____MULTIPART_MIXED_BOUNDARY____
Content-Type: multipart/alternative; boundary="=_____MULTIPART_ALTERNATIVE_BOUNDARY____";

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

2point4
------------------------------------------------------
Order Number: 1
Detailed Invoice: https://www.somewebsite.com/2point4/account_history_info.php?order_id=1
Date Ordered: Tuesday 15 November, 2016

The comments for your order are

Your order has been updated to the following status.
New status: Processing
Please reply to this email if you have any questions.

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: multipart/related; boundary="=_____MULTIPART_RELATED_BOUNDARY____"

--=_____MULTIPART_RELATED_BOUNDARY____
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

2point4
------------------------------------------------------
Order Number: 1
Detailed Invoice: https://www.somewebsite.com/2point4/account_history_info.php?order_id=1
Date Ordered: Tuesday 15 November, 2016

The comments for your order are

Your order has been updated to the following status.
New status: Processing
Please reply to this email if you have any questions.

--=_____MULTIPART_RELATED_BOUNDARY____--

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____--

--=_____MULTIPART_MIXED_BOUNDARY____--

**Comment by Gergely** [comment]
Thanks!

html part of the Multipart Boundary is not html. There should be HTML coded text (text/html)
Checkout_process generate plain text and no html formatted codes for emails. So there are no **<br />** tags only **"\n"** in line feeds which will never break lines in html context.
Previous versions of oscommerce not folowed the right boundary standards so it was possible to inject into the mail body directly formatted codes.

Fixes need in core before email sendings.

**Comment by Gergely** [comment]
Could you test it?

https://github.com/Gergely/oscommerce2/commit/13a7084005aad5ec1811e628caa0b9b4706075d2

**Comment by frankludriks** [comment]
This is the output with your change

Return-Path: <sales@somewebsite.com>
Delivered-To: frank@someotherwebsite.com.au
Received: from somewebsite.com
	by someotherwebsite.com.au (Dovecot) with LMTP id yUJ6B7vkLFh5JwAAPuX4MA
	for <frank@someotherwebsite.com.au>; Thu, 17 Nov 2016 09:59:07 +1100
Return-path: <sales@somewebsite.com>
Envelope-to: frank@someotherwebsite.com.au
Delivery-date: Thu, 17 Nov 2016 09:59:07 +1100
Received: from top by somewebsite.com with local (Exim 4.87)
	(envelope-from <sales@somewebsite.com>)
	id 1c79AZ-0002jF-0R
	for frank@someotherwebsite.com.au; Thu, 17 Nov 2016 09:59:07 +1100
To: "Frank L" <frank@someotherwebsite.com.au>
Subject: Order Update
X-PHP-Script: www.somewebsite.com/2point4/admin/orders.php for 203.206.167.117
X-Mailer: osCommerce
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=_____MULTIPART_MIXED_BOUNDARY____"
Content-Transfer-Encoding: 7bit
From: "2point4" <sales@somewebsite.com>
Message-Id: <E1c79AZ-0002jF-0R@somewebsite.com>
Date: Thu, 17 Nov 2016 09:59:07 +1100

This is a multi-part message in MIME format.

--=_____MULTIPART_MIXED_BOUNDARY____
Content-Type: multipart/alternative; boundary="=_____MULTIPART_ALTERNATIVE_BOUNDARY____";

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

2point4------------------------------------------------------Order Number: 3Detailed Invoice: https://www.somewebsite.com/2point4/account_history_info.php?order_id=3Date Ordered: Thursday 17 November, 2016The comments for your order areYour order has been updated to the following status.New status: ProcessingPlease reply to this email if you have any questions.

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: multipart/related; boundary="=_____MULTIPART_RELATED_BOUNDARY____"

--=_____MULTIPART_RELATED_BOUNDARY____
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

2point4<br>------------------------------------------------------<br>Order Number: 3<br>Detailed Invoice: https://www.somewebsite.com/2point4/account_history_info.php?order_id=3<br>Date Ordered: Thursday 17 November, 2016<br><br>The comments for your order are<br><br><br>Your order has been updated to the following status.<br>New status: Processing<br>Please reply to this email if you have any questions.<br>

--=_____MULTIPART_RELATED_BOUNDARY____--

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____--

--=_____MULTIPART_MIXED_BOUNDARY____--

**Comment by Gergely** [comment]
Could you copy/paste with "insert code"? (I used html insert code formula) I dont see `<br>`
Its working for me but as Harald said plan text line breaks `"\n"` and html breaks tag from language text defs results in duplicated line breaks.

```html
This is a multi-part message in MIME format.

--=_____MULTIPART_MIXED_BOUNDARY____
Content-Type: multipart/alternative; boundary="=_____MULTIPART_ALTERNATIVE_BOUNDARY____";

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

Oscommerce v2.4 project------------------------------------------------------Order Number: 13Detailed Invoice: http://localhost/projects/oscom24_g/catalog/account_history_info.php?order_id=13Date Ordered: Wednesday 16 November, 2016The comments for your order aresdfgsdf
sdfgsdfgs
sdfgsdfg
gYour order has been updated to the following status.New status: PendingPlease reply to this email if you have any questions.

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: multipart/related; boundary="=_____MULTIPART_RELATED_BOUNDARY____"

--=_____MULTIPART_RELATED_BOUNDARY____
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

Oscommerce v2.4 project<br>------------------------------------------------------<br>Order Number: 13<br>Detailed Invoice: http://localhost/projects/oscom24_g/catalog/account_history_info.php?order_id=13<br>Date Ordered: Wednesday 16 November, 2016<br><br>The comments for your order are<br>sdfgsdf
<br>sdfgsdfgs
<br>sdfgsdfg
<br>g<br><br>Your order has been updated to the following status.<br>New status: Pending<br>Please reply to this email if you have any questions.<br>

--=_____MULTIPART_RELATED_BOUNDARY____--

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____--

--=_____MULTIPART_MIXED_BOUNDARY____--```

Question is what will be the rule for emails: html or text from language files?

**Comment by haraldpdl** [comment]
Emails will need to have two versions: plain text and html. Until the admin page is ready to manage emails, both plain text and html versions of an email must exist in the language definition file.

Plain text should be sent as is even if it includes html tags (no strip_tags()).
HTML should be sent as is (no nl2br()).

If only a text version is provided, a HTML version can be formed using nl2br().
If only a HTML version is provided, a plain text version can be formed using strip_tags() and a custom br2nl() function.

**Comment by Gergely** [comment]
Thanks @haraldpdl 

Something like this may be help without language definitions
```PHP
    public function isBodyHTML()
    {
      return ($this->body_html == $this->body_plain);
    }
```

**Comment by frankludriks** [comment]
Hope this helps

`Return-Path: <sales@somewebsite.com.au>
Delivered-To: frank@someotherwebsite.com.au
Received: from somewebsite.com
	by someotherwebsite.com (Dovecot) with LMTP id yUJ6B7vkLFh5JwAAPuX4MA
	for <frank@someotherwebsite.com.au>; Thu, 17 Nov 2016 09:59:07 +1100
Return-path: <sales@somewebsite.com.au>
Envelope-to: frank@someotherwebsite.com.au
Delivery-date: Thu, 17 Nov 2016 09:59:07 +1100
Received: from somewebsite by someotherwebsite with local (Exim 4.87)
	(envelope-from <sales@somewebsite.com.au>)
	id 1c79AZ-0002jF-0R
	for frank@someotherwebsite.com.au; Thu, 17 Nov 2016 09:59:07 +1100
To: "Frank L" <frank@someotherwebsite.com.au>
Subject: Order Update
X-PHP-Script: www.somewebsite.com/2point4/admin/orders.php for 203.206.167.117
X-Mailer: osCommerce
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=_____MULTIPART_MIXED_BOUNDARY____"
Content-Transfer-Encoding: 7bit
From: "2point4" <sales@somewebsite.com>
Message-Id: <E1c79AZ-0002jF-0R@somewebsite.com>
Date: Thu, 17 Nov 2016 09:59:07 +1100

This is a multi-part message in MIME format.

--=_____MULTIPART_MIXED_BOUNDARY____
Content-Type: multipart/alternative; boundary="=_____MULTIPART_ALTERNATIVE_BOUNDARY____";

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

2point4------------------------------------------------------Order Number: 3Detailed Invoice: https://www.somewebsite.com/2point4/account_history_info.php?order_id=3Date Ordered: Thursday 17 November, 2016The comments for your order areYour order has been updated to the following status.New status: ProcessingPlease reply to this email if you have any questions.

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____
Content-Type: multipart/related; boundary="=_____MULTIPART_RELATED_BOUNDARY____"

--=_____MULTIPART_RELATED_BOUNDARY____
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

2point4<br>------------------------------------------------------<br>Order Number: 3<br>Detailed Invoice: https://www.somewebsite.com.au/2point4/account_history_info.php?order_id=3<br>Date Ordered: Thursday 17 November, 2016<br><br>The comments for your order are<br><br><br>Your order has been updated to the following status.<br>New status: Processing<br>Please reply to this email if you have any questions.<br>

--=_____MULTIPART_RELATED_BOUNDARY____--

--=_____MULTIPART_ALTERNATIVE_BOUNDARY____--

--=_____MULTIPART_MIXED_BOUNDARY____--


`

**Comment by Gergely** [comment]
@frankludriks 
I have figured out a simple html part for checkout
https://github.com/osCommerce/oscommerce2/compare/master...Gergely:issue_499

and normal html parts for account and pasword forgotten as @haraldpdl mentioned before.

Could you test it? Only **checkout_process.php** is the required file changes for you.

**Comment by Gergely** [comment]
Thanks!
