### ISSUE TITLE
Database backup fails

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#503]
Attempting to backup database through Shop -> Tools -> Database Backup (admin/backup.php?action=backup) results in a 500 error.

From log file:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tonerpak_2point4.osc_osc_action_recorder' doesn't exist' in /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php:94
Stack trace:
#0 /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php(94): PDO->query('select id, modu...')
#1 /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php(142): OSC\OM\Db->query('select id, modu...')
#2 /home/somewebsite/public_html/2point4/admin/backup.php(124): OSC\OM\Db->get('osc_action_reco...', Array)
#3 {main}
  thrown in /home/somewebsite/public_html/2point4/includes/OSC/OM/Db.php on line 94

**Comment by scottcwilson** [comment]
Replicated.  Looks like prefix is being added twice.

**Comment by Gergely** [comment]
I have different problem with schema

> [17-Nov-2016 15:03:52 Europe/Budapest] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oscom24.osc_counter' doesn't exist in C:\wamp\www\projects\oscom24_g\catalog\includes\OSC\OM\Db.php:94
Stack trace:
#0 C:\wamp\www\projects\oscom24_g\catalog\includes\OSC\OM\Db.php(94): PDO->query('select startdat...')
#1 C:\wamp\www\projects\oscom24_g\catalog\includes\OSC\OM\Db.php(142): OSC\OM\Db->query('select startdat...')
#2 C:\wamp\www\projects\oscom24_g\catalog\admin\backup.php(124): OSC\OM\Db->get(Array, Array)
#3 {main}
  thrown in C:\wamp\www\projects\oscom24_g\catalog\includes\OSC\OM\Db.php on line 94

**Comment by Gergely** [comment]
but the reason the same. You can get an error if new osc schema tables installed with previous version.

**Comment by Gergely** [comment]
Backup mechanism scans non-prefix tables but try to save prefixed table values

**Comment by Gergely** [comment]
@haraldpdl 

Is it possible like filter in where clause in `Db->Get` ? Maybe its would be better prepare and run query directly with prefix. Is there any reason to use Get function here?

**Comment by Gergely** [comment]
Could you test it?

https://github.com/osCommerce/oscommerce2/compare/master...Gergely:issue_503

**Comment by frankludriks** [comment]
Backup worked with that change Gergely.

**Comment by haraldpdl** [comment]
Fixed in #540 🍻
