### ISSUE TITLE
Error when viewing currencies admin page

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#506]
When navigating to admin/currencies.php no error with the page, but the error log shows:

PHP Notice:  DateTime:  () cannot be formatted to Y-m-d H:i:s in /home/somewebsite/public_html/2point4/includes/OSC/OM/DateTime.php on line 52

**Comment by scottcwilson** [comment]
Fixed in PR #523

**Comment by Gergely** [comment]
Thanks! Your fixes prevent conflicts

Development notice:  

> date added field is missing from curriencies table
> Reason: unknown

**Comment by scottcwilson** [comment]
sorry, I fat fingered it when I did it this morning.  Should be ok now.
