### ISSUE TITLE
Emails not sending from admin

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#507]
Navigated to Legacy -> Tools -> Send Email

Sent an email to customer, customer did not receive it

(test newsletter sent and received fine)

**Comment by Gergely** [comment]
@frankludriks 
Its sending from desktop development enviroment. What was the fail?

> Mail delivery failed: returning message to sender

**Comment by frankludriks** [comment]
Silent fail.

**Comment by Gergely** [comment]
Something another is found. 

The following mime part is missing after second emails:

`MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=_____MULTIPART_MIXED_BOUNDARY____"
Content-Transfer-Encoding: 7bit`

**Comment by Gergely** [comment]
@frankludriks

If you send newsletter to all customers (at least 2) than the second email is recived?

Here is a fix: https://github.com/osCommerce/oscommerce2/commit/191e4369067c6bcc1758a5f4f76e2cb9195f7583

**Comment by haraldpdl** [comment]
@Gergely PR #541 might be a better solution. Can you review and confirm? Thanks!
