### ISSUE TITLE
Tax Classes Page Error

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#508]
When visiting the page Legacy -> Locations/Taxes -> Tax Classes the page loads as normal but will log the following error:

PHP Notice:  DateTime:  () cannot be formatted to Y-m-d H:i:s in /home/somewebsite/public_html/2point4/includes/OSC/OM/DateTime.php on line 52

**Comment by scottcwilson** [comment]
Can't dup this either.

**Comment by frankludriks** [comment]
Sorry, need to add a new tax class first then the error shows up.

**Comment by scottcwilson** [comment]
OK. It's the act of adding a new tax class that causes the issue.  Submitted PR #522
