### ISSUE TITLE
Error in Tax Zones page

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#509]
Navigate to page Legacy -> Locations/Taxes -> Tax Zones

Page loads normally but logs the following errors:

PHP Warning:  array_merge(): Argument #2 is not an array in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 231
PHP Warning:  Invalid argument supplied for foreach() in /home/somewebsite/public_html/2point4/admin/includes/classes/object_info.php on line 13
PHP Notice:  Undefined property: objectInfo::$geo_zone_id in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 234
PHP Notice:  Undefined property: objectInfo::$geo_zone_id in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 241
PHP Notice:  Undefined property: objectInfo::$geo_zone_id in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 234
PHP Notice:  Undefined property: objectInfo::$geo_zone_id in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 241
PHP Notice:  Undefined property: objectInfo::$geo_zone_id in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 255
PHP Notice:  Undefined property: objectInfo::$geo_zone_name in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 334
PHP Notice:  Undefined property: objectInfo::$geo_zone_id in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 336
PHP Notice:  Undefined property: objectInfo::$num_zones in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 337
PHP Notice:  Undefined property: objectInfo::$date_added in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 338
PHP Notice:  DateTime:  () cannot be formatted to Y-m-d H:i:s in /home/somewebsite/public_html/2point4/includes/OSC/OM/DateTime.php on line 52
PHP Notice:  Undefined property: objectInfo::$last_modified in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 339
PHP Notice:  Undefined property: objectInfo::$geo_zone_description in /home/somewebsite/public_html/2point4/admin/geo_zones.php on line 340

**Comment by Gergely** [comment]
I can not repeat it.

**Comment by scottcwilson** [comment]
I can't replicate either; fresh download today.

**Comment by frankludriks** [comment]
Sorry, need to add a new tax zone then the error will appear.

**Comment by Gergely** [comment]
Thanks!

Hmm.. this is a possible fix but not the best.

https://github.com/osCommerce/oscommerce2/compare/master...Gergely:issue_509

@haraldpdl 
when count is zero then fetch and toArray give back false

**Comment by haraldpdl** [comment]
@Gergely Thanks for that fix. The "group by" is not needed though so a simpler fix was merged in.

MySQL does not return 0 when "select count(*)" is used with "group by" and no records exist - it returns "null" which is why our toArray() method was empty.
