### ISSUE TITLE
Missing language definition in Also Purchased module

### ISSUE THREAD

**Issue by frankludriks** [osCommerce/oscommerce2#511]
When Also Purchased module is shown, language definition is missing

From error log:

PHP Notice:  Use of undefined constant TEXT_ALSO_PURCHASED_PRODUCTS - assumed 'TEXT_ALSO_PURCHASED_PRODUCTS' in /home/somewebsite/public_html/2point4/includes/content/also_purchased_products.php on line 43

**Comment by haraldpdl** [comment]
Duplicate #480
