### ISSUE TITLE
Notice: DateTime: () cannot be formatted t

### ISSUE THREAD

**Issue by oitsuki** [osCommerce/oscommerce2#533]
I don't know if it's exactly a bug, but when inside the database , a date fields is on null there is an error
example
```
DateTime::toShort($Qcategories->value('last_modified')
if $Qcategories->value('last_modified') is null this error can appear :
Notice: DateTime: () cannot be formatted to Y-m-d H:i:s in /home/www/...../DateTime.php
```

ErrorHandler.php change
`      ini_set('display_errors', true);`

To test
edit categories in database, change the last modified date fields by null
go in admin/categories.php

**Comment by haraldpdl** [comment]
Is this happening on code you are writing yourself? I don't see where this is happening in the core code.

If it is your code, then you have to check if last_modified has a value or not before using DateTime on it. DateTime has strict checks to improve the developers code 😃 Please see PR #530 as an example.

**Comment by oitsuki** [comment]
Oups sorry, yes you are right, I separated categories and products 2 files) and rewrite the code in consequence. 
Next time I must becarefull (more and verify) and I don't want you lost your time.
But I think this pb touch all the files use DateTime with a date in Db is the date is null and not fill. 
I saw in commit some point about that.
