### ISSUE TITLE
Attachment icon displayed with osc emails

### ISSUE THREAD

**Issue by Gergely** [osCommerce/oscommerce2#552]
Something confused in mail parts. Attachment icon appears.

**Comment by Gergely** [comment]
Some primitive online email cliens display attachment icons if multipart mixed boundaries or related boundary is added.
If only multipart/alternative used then no attachment icons.

So if no attachment then only **mutipart/alternative** boundary should be used.

**Comment by haraldpdl** [comment]
Can a screenshot be provided of the icon? Thanks!

**Comment by Gergely** [comment]
![attachment_icon](https://cloud.githubusercontent.com/assets/284010/20532759/61ec25c2-b0db-11e6-8d62-5df6fecd45e0.PNG)

**Comment by Gergely** [comment]
Hi Harald,

I walked around the problem and your concept is the best. Some email service drop emails only with
**Content-Type: multipart/alternative** bondary even if we use with **multipart/mixed** in SMTP transports.
The simple **Content-Type: multipart/alternative** works only with sendmails.
