### ISSUE TITLE
VR-Pay oscommerce 2.3.4 header problem on Checkout

### ISSUE THREAD

**Issue by Darkness1210** [osCommerce/oscommerce2#572]
Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/xxxxx/xxxxxxxxxxx.com/catalog/includes/modules/boxes/bm_featured.php:2) in /www/htdocs/v1316xxxxx/xxxxxxxxxxx.com/catalog/includes/functions/general.php on line 51

The Module is clean installed. Also a clean OSCommerce 2.3.4 Version

**Comment by haraldpdl** [comment]
This isn't part of the core - it would be best to ask in the forums. For general "headers already sent" errors, you will need to edit the file specified in the error message and make sure no whitespace exists at the top of the file before the opening php tag <?php
