### ISSUE TITLE
Paypal App not updating

### ISSUE THREAD

**Issue by drillsar** [osCommerce/oscommerce2#594]
Says version 5.018 available but says need to do manually. However, no version is located in apps just version 5.010. Update button not visible

**Comment by drillsar** [comment]
Nevermind missing ziparchive

**Comment by haraldpdl** [comment]
Thanks for reporting back. The 5.018 version was not made publicly available to broaden the audience performing online updates (server environment testing purposes). 5.018 will be made publicly available with the next update to the App, and future updates will also be made available immediately for manual upgrades.
